### PR TITLE
Rename env.sample to .env.sample

### PR DESCRIPTION
**Pull request by TheodoreChu**
Rename `env.sample` to `.env.sample` as discussed here: https://app.asana.com/0/1178618677234188/1195916508730187

### CODE REVIEW

**Comment by johnny243** [comment]
Nice! Can you update https://github.com/standardnotes/docs also?

**Comment by TheodoreChu** [comment]
Yes, I'll do that after this is merged 👍

**Comment by mobitar** [comment]
Involves GitHub workflows so will need @karolsojko to approve this.

**Review by karolsojko — APPROVED** [review]

**Comment by TheodoreChu** [comment]
Do I merge this now? GitHub is saying "This branch has conflicts that must be resolved". When I use the command line to resolve conflicts, I get this error:
```
fatal: remote error:
  You can't push to git://github.com/standardnotes/syncing-server.git
```
I think I may not have sufficient permissions. Is that right?

**Comment by mobitar** [comment]
You have to run `git pull origin develop` locally, and fix the resulting merge conflict. Then commit and push up the changes.

**Comment by TheodoreChu** [comment]
I had to run `git remote set-url origin git@github.com:standardnotes/syncing-server.git` and it worked

**Pull request merged**
