### PR TITLE
fix: upgrade docker-compose.*.yml to 3.8

### LINKED ISSUE #92: Raspberry pi docker-compose version mismatch
git pull then set my .env file then ran the docker-compose command then was met with

```
docker-compose -f docker-compose.yml -f docker-compose.raspberry-pi.yml up -d
ERROR: Version mismatch: file ./docker-compose.yml specifies version 3.8 but extension file ./docker-compose.raspberry-pi.yml uses version 3.0
```

changing the raspberrypi.yml version seems to fix

### PR DESCRIPTION
**Pull request by johnny243**
Closes #92

### CODE REVIEW

**Comment by karolsojko** [comment]
The inention of `docker-compose` is to create a local development only environment for contributing purposes. As mentioned in here https://github.com/standardnotes/syncing-server#contributing

For production or running in other environments a pre-built image should be used from Docker Hub as mentioned in here: https://github.com/standardnotes/syncing-server#docker-setup

having that in mind I think we should remove `docker-compose.raspberry-pi.yml` and `docker-compose.development.yml` files as I'm not sure what their purpose is anymore.

@johnny243 @mobitar wdyt?

**Comment by johnny243** [comment]
`docker-compose.development.yml` was created to override the environment variable and set it to `development`. I'm ok of removing this, but we should keep `docker-compose.raspberry-pi.yml` for now (an image can be created in the future).

**Comment by karolsojko** [comment]
We can remove the rpi one as well - just add another `docker tag ...` and `docker push...` in the github actions when it builds the images

**Comment by johnny243** [comment]
Great! Will look into that later :+1: Closing.

**Pull request closed without merging**
