### PR TITLE
fix: revision response

### PR DESCRIPTION
**Pull request by johnny243**
- [x] updates the response for the `/items/:item_id/revisions` endpoint
- [x] updates the response for the `/items/:item_id/revisions/:id` endpoint

### CODE REVIEW

**Comment by mobitar** [comment]
@karolsojko do you mean why we are wrapping the revision response in a hash rather than returning it as the top level response item?

**Comment by karolsojko** [comment]
> @karolsojko do you mean why we are wrapping the revision response in a hash rather than returning it as the top level response item?

exactly :)

**Comment by mobitar** [comment]
I don't know, what's your take on this? I believe we did this because it was awkward that a response could have properties like response.status, response.error, and response.items_key_id (a revision property). There wasn't a clear separation of what properties belonged to the revision and what properties belonged to the http response. Whereas returning it as a nested object always makes sure you're accessing exactly revision properties.

**Comment by karolsojko** [comment]
does `items_key_id` belong to `response.body` which is at the same level as `response.status` and `response.error` ?

**Comment by mobitar** [comment]
Yes, that's the current behavior. What I'm saying is that these should not be on the same level because they are unrelated.

**Comment by karolsojko** [comment]
hmm it feels kind of weird to me when I want to get a single REST resource to get an array with one element. I'm not sure I understand what's wrong with this HTTP Response schema:

```
response:
- status: 200
- error: null
- body:
--id: 123
--name: test
```

Feels natural to call a REST endpoint for example `/books` and traverse the response as an array, also the same for `/books/:id` and getting a specific object. wrapping it up adds a layer of complexity to the client to parse the response don't you think?

**Comment by mobitar** [comment]
I've always been torn on this issue ;) Can never settle on one style or the other. But if you think returning the desired resource on the same level as other HTTP-related properties is perfectly fine then I'm ok going with that 👍 @johnny243 we can scrap this PR

**Comment by mobitar** [comment]
Actually nevermind, it was our client HTTP service that was combining body fields into the top level response object: https://github.com/standardnotes/snjs/blob/004/lib/services/api/http_service.ts#L112. So we can close this and address this client side.

**Pull request closed without merging**
