### PR TITLE
feat: Add daily backups jobs triggering from a controller

### PR DESCRIPTION
**Pull request by karolsojko**
Changed the way the `daily backup jobs` will be triggered. 

We can't run a cron job on every container that the app is running because that would lead to multiple overlapping backups + hazards. 

Instead I've copied the business logic of the rake job into the admin controller that is protected by the `ADMIN_KEY` environment variable (also allowed only from a certain source).

This controller method will be triggered by a scheduled AWS Lambda function - the same frequency as the cron was. 

This way we retain the the possibility to do `deliver_later` and `perform_later` on jobs and also are guaranteed that this will be triggered only once daily.

### CODE REVIEW

**Comment by mobitar** [comment]
Interesting approach. I think this could work. Do you want to keep legacy cronjob code as well (`whenever` gem, `rake` task)?

**Comment by karolsojko** [comment]
> Interesting approach. I think this could work. Do you want to keep legacy cronjob code as well (`whenever` gem, `rake` task)?

@mobitar I first deleted it, but then I thought that some users might preffer cron over HTTP so we can keep both options there - wdyt ?

**Comment by mobitar** [comment]
Hmm yeah, true. Is there anyway we can accomplish both options without code duplication? Can rake task access controller function?

**Comment by karolsojko** [comment]
Closing this up - based on the discussion with @mobitar we will run cron jobs on AWS scheduled tasks

**Pull request closed without merging**
